# DigitalOcean App Platform Configuration
# for Read-Only Odoo MCP Server

name: odoo-mcp-readonly
region: fra

services:
- name: odoo-mcp-server
  source_dir: /
  github:
    repo: actec-andre/mcp-odoo-v16-read-only
    branch: main
    deploy_on_push: true

  run_command: python -m uvicorn src.odoo_mcp.server:mcp --host 0.0.0.0 --port 8080

  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs

  http_port: 8080

  envs:
  # Odoo Connection - Staging Environment
  - key: ODOO_URL
    value: https://rhholding-merge-add-sscc-23727788.dev.odoo.com
  - key: ODOO_DB
    value: rhholding-merge-add-sscc-23727788
  - key: ODOO_USERNAME
    value: mcp@ananda.gmbh
  - key: ODOO_PASSWORD
    value: mcp88

  # Odoo Client Configuration
  - key: ODOO_TIMEOUT
    value: "30"
  - key: ODOO_VERIFY_SSL
    value: "1"

  # Monitoring (optional)
  - key: LOG_LEVEL
    value: INFO

# Optional: Database for caching/session storage
# databases:
# - name: mcp-cache
#   engine: PG
#   version: "14"
#   size: db-s-dev-database

# Optional: Redis for rate limiting
# - name: mcp-redis
#   engine: REDIS
#   version: "7"
#   size: db-s-dev-database

# Domain configuration (will be auto-generated if not specified)
domains:
- domain: odoo-mcp.rhholding.com
  type: PRIMARY

# Optional: Static site for documentation
# static_sites:
# - name: mcp-docs
#   source_dir: /docs
#   github:
#     repo: your-username/odoo-read-only-mcp
#     branch: main
#   build_command: echo "No build needed"
#   output_dir: /docs
#   index_document: README.md